version: '3.1'
services:
  login:
    build: './api/login'
    ports:
      - '3001:3000'
    volumes:
      - ./api/util:/login/src/util
    depends_on:
      - db
    environment:
      - DB_HOST=db

  signup:
    build: './api/signup'
    ports:
      - '3002:3000'
    volumes:
      - ./api/util:/signup/src/util
    depends_on:
      - db
    environment:
      - DB_HOST=db

  register:
    build: './api/register'
    ports:
      - '3003:3000'
    volumes:
      - ./api/util:/register/src/util
    depends_on:
      - db
    environment:
      - DB_HOST=db

  registration:
    build: './api/registration'
    ports:
      - '3004:3000'
    volumes:
      - ./api/util:/registration/src/util
    depends_on:
      - db
    environment:
      - DB_HOST=db

  cancel:
    build: './api/cancel'
    ports:
      - '3005:3000'
    volumes:
      - ./api/util:/cancel/src/util
    depends_on:
      - db
    environment:
      - DB_HOST=db

  checkin:
    build: './api/checkin'
    ports:
      - '3006:3000'
    volumes:
      - ./api/util:/checkin/src/util
    depends_on:
      - db
    environment:
      - DB_HOST=db

  certificate:
    build: './api/certificate'
    ports:
      - '3007:3000'
    volumes:
      - ./api/util:/certificate/src/util
    depends_on:
      - db
    environment:
      - DB_HOST=db

  validate:
    build: './api/validate'
    ports:
      - '3008:3000'
    volumes:
      - ./api/util:/validate/src/util
    depends_on:
      - db
    environment:
      - DB_HOST=db

  mail:
    build: './api/mail'
    ports:
      - '3009:3000'
    volumes:
      - ./api/util:/mail/src/util
    depends_on:
      - db
    environment:
      - DB_HOST=db

  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:mysql://db -schemas=eventos -user=root -password=root -connectRetries=60 migrate
    volumes:
      - ./api/migrations:/flyway/sql
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_volume:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - '8080:8080'
    volumes:
      - ./client:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - login
      - signup
      - register
      - cancel
      - checkin
      - certificate

volumes:
  db_volume:
